---
alias: "Front door opened notification"
id: '1660659401400'
description: >-
  Notifies when the front door has been opened.
trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    from: 'off'
    to: 'on'
condition: []
action:
  - device_id: bfa77c3162ec6c591cc2aaf4407291d2
    domain: mobile_app
    type: notify
    message: Front door was opened
    title: Front door opened
  - device_id: 6eef301d86f27cab07a69158b51cda45
    domain: mobile_app
    type: notify
    title: Front door opened
    message: Front door was opened
mode: single
