---
alias: "Front door closed notification"
id: '1660659475650'
description: >-
  Notifies when the front door has been closed.
trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    from: 'on'
    to: 'off'
condition: []
action:
  - service: notify.mobile_app_ledena_sumica_2_0_3
    data:
        message: Front door was closed
  - service: notify.mobile_app_aleksandras_iphone
    data:
        message: Front door was closed
mode: parallel